"""add_is_deleted_to_kb_and_documents

Revision ID: 085b5c6006f6
Revises: a1b728a152cf
Create Date: 2026-04-29 20:50:56.339844

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '085b5c6006f6'
down_revision: Union[str, Sequence[str], None] = 'a1b728a152cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('knowledge_bases', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('knowledge_bases', 'is_deleted')
    op.drop_column('documents', 'is_deleted')
    # ### end Alembic commands ###
