"""add object_key to documents

Revision ID: a1b728a152cf
Revises: 3f6bb224b72f
Create Date: 2026-04-28 20:20:42.408960

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1b728a152cf'
down_revision: Union[str, Sequence[str], None] = '3f6bb224b72f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('object_key', sa.String(length=1024), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'object_key')
    # ### end Alembic commands ###
